# Generated by Django 5.0.2 on 2024-03-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_contactformmessage_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='smtpport',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
